name: "Ambit Energy Scraper"
description: "Scrape Ambit Energy usage data and send it to Home Assistant"
version: "1.0.0"
slug: "ambit_energy_scraper"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  username: "your_username"
  password: "your_password"
  ha_url: "http://homeassistant.local:8123"
  ha_token: "your_long_lived_token"
schema:
  - name: username
    type: string
    required: true
    description: "Your Ambit Energy account username"
  - name: password
    type: string
    required: true
    description: "Your Ambit Energy account password"
  - name: ha_url
    type: string
    required: true
    description: "Home Assistant URL (e.g., http://homeassistant.local:8123)"
  - name: ha_token
    type: string
    required: true
    description: "Long-lived Home Assistant access token"

