name: "Ambit Energy Scraper"
description: "Scrape Ambit Energy usage data and send it to Home Assistant"
version: "1.0.0"
slug: "ambit_energy_scraper"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  username: "your_username"
  password: "your_password"
  ha_url: "http://homeassistant.local:8123"
  ha_token: "your_long_lived_token"
schema:
  username: "str"
  password: "str"
  ha_url: "str"
  ha_token: "str"

