name: Ambit Energy Scraper
version: "1.0.0"
slug: ambit_energy_scraper
description: "Extract Ambit Energy consumption data and send it to Home Assistant."
url: https://github.com/your-repo/ambit_energy_scraper
arch:
  - aarch64
  - amd64
  - armv7
init: false
codenotary: null
options:
  username: "YOUR_AMBIT_USERNAME"
  password: "YOUR_AMBIT_PASSWORD"
  ha_token: "YOUR_LONG_LIVED_ACCESS_TOKEN"
  ha_url: "http://homeassistant:8123"
  interval_hours: 6
schema:
  username: str
  password: str
  ha_token: str
  ha_url: str
  interval_hours: int(1,24)

