name: "Ambit Energy Scraper"
description: "Scrape Ambit Energy usage data and send it to Home Assistant"
version: "1.0.1"
slug: "ambit_energy_scraper"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  username: "your_username"
  password: "your_password"
  ha_url: "http://homeassistant.local:8123"
  ha_token: "your_long_lived_token"
schema:
  - name: "username"
    description: "Your Ambit Energy account username"
    type: "str"
    required: true
  - name: "password"
    description: "Your Ambit Energy account password"
    type: "str"
    required: true
  - name: "ha_url"
    description: "Home Assistant URL (e.g., http://homeassistant.local:8123)"
    type: "str"
    required: true
  - name: "ha_token"
    description: "Long-lived Home Assistant access token"
    type: "str"
    required: true
