name: "Ambit Energy Scraper"
description: "Scrapes energy consumption data from Ambit Energy and sends it to Home Assistant."
version: "1.0.0"
slug: "ambit_energy_scraper"
startup: "application"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  username: "secret.ambit_username"
  password: "secret.ambit_password"
  ha_url: "secret.ha_url"
  ha_token: "secret.ha_token"
schema:
  username:
    type: str
    description: "Tu nombre de usuario de Ambit Energy"
    required: true
  password:
    type: str
    description: "Tu contraseña de Ambit Energy"
    required: true
  ha_url:
    type: str
    description: "URL de Home Assistant (e.g., http://homeassistant.local:8123)"
    required: true
  ha_token:
    type: str
    description: "Token de acceso de larga duración de Home Assistant"
    required: true
image: "local/ambit_energy_scraper"
logo: "https://github.com/lam1623/ambit_energy_scraper/blob/main/ambit_energy_scraper/ambitenergy-logo.svg?raw=true"
documentation: "https://github.com/lam1623/ambit_energy_scraper/blob/main/ambit_energy_scraper/README.md"
map:
  - "config"
  - "ssl"
  - "share"
  - "backup"
environment:
  USERNAME: "secret.ambit_username"
  PASSWORD: "secret.ambit_password"
  HA_URL: "secret.ha_url"
  HA_TOKEN: "secret.ha_token"
privileged: false
devices: []
host_network: false
workdir: "/app"

