name: "Ambit Energy Scraper"
description: "Scrape energy usage from Ambit Energy and send it to Home Assistant"
version: "1.0.0"
slug: "ambit_energy_scraper"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  username: "your_username"
  password: "your_password"
  ha_url: "http://homeassistant.local:8123"
  ha_token: "your_long_lived_token"
schema:
  username:
    type: str
    description: "Your Ambit Energy account username"
    required: true
  password:
    type: str
    description: "Your Ambit Energy account password"
    required: true
  ha_url:
    type: str
    description: "Home Assistant URL (e.g., http://homeassistant.local:8123)"
    required: true
  ha_token:
    type: str
    description: "Long-lived Home Assistant access token"
    required: true

