options:
  username: "secret.ambit_username"
  password: "secret.ambit_password"
  ha_url: "http://homeassistant.local:8123"
  ha_token: "secret.ha_token"
schema:
  username:
    type: str
    description: "Tu nombre de usuario de Ambit Energy"
    required: true
  password:
    type: str
    description: "Tu contraseña de Ambit Energy"
    required: true
  ha_url:
    type: str
    description: "URL de Home Assistant (e.g., http://homeassistant.local:8123)"
    required: true
  ha_token:
    type: str
    description: "Token de acceso de larga duración de Home Assistant"
    required: true

